import { Inter } from "next/font/google";
import Navegation from "@/app/components/navegation.jsx";
import Footer from "@/app/components/footer.jsx";
import "@/app/style/root.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navegation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
